title: Test
author: This is a test
email: your-email@domain.com
description: Testing...
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: false

theme: minima
