title: How To Fit In
author: Coolio 
email: suckstoyourass-mar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   
theme: minima

# social links
twitter_username: User3841
Github_username: Piggy2828

show_excerpts: false
