title: This is a title.
author: Anonymous
email: followinauntie281@gmail.com
description: 
# social links
twitter_username: @followinauntie
github_username:  Followin Auntie

show_excerpts: false

theme: minima
